# Generated by Django 5.2.4 on 2025-07-23 17:35

import django.db.models.deletion
import django.utils.timezone
import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=255, unique=True)),
                ('base_price_per_meter', models.FloatField(default=2000)),
                ('floor', models.IntegerField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('height', models.FloatField()),
                ('features', models.TextField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='warehouse_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=warehouse.models.month_more)),
                ('price_per_day_overdue', models.FloatField(default=100)),
                ('string_for_qr_code', models.UUIDField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='warehouse.warehouse'),
        ),
    ]
