# Generated by Django 5.2.4 on 2025-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
