# Generated by Django 5.2.4 on 2025-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_order_overdue_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='overdue_notified',
        ),
        migrations.AddField(
            model_name='order',
            name='last_overdue_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление о просрочке'),
        ),
    ]
