# Generated by Django 5.2.4 on 2025-07-28 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='string_for_qr_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
