# Generated by Django 5.2.4 on 2025-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_order_string_for_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
