# Generated by Django 5.2.4 on 2025-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_order_adv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_14d_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_3d_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_7d_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
