# Generated by Django 5.2.4 on 2025-07-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('slogan', models.CharField(max_length=100, verbose_name='Слоган')),
                ('text', models.TextField(verbose_name='Основной текст отзыва')),
                ('photo', models.ImageField(upload_to='reviews/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
